/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Label = IDL.Variant({ 'ham' : IDL.Null, 'spam' : IDL.Null });
export const ClassificationRecord = IDL.Record({
  'id' : IDL.Nat,
  'classificationLabel' : Label,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func([IDL.Text, Label, IDL.Float64], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(ClassificationRecord)], ['query']),
  'seedDemoData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Label = IDL.Variant({ 'ham' : IDL.Null, 'spam' : IDL.Null });
  const ClassificationRecord = IDL.Record({
    'id' : IDL.Nat,
    'classificationLabel' : Label,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func([IDL.Text, Label, IDL.Float64], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(ClassificationRecord)], ['query']),
    'seedDemoData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };